# rosparam load labels.yaml /label_detector/hzl_scanner/labels_names


########## only JPG!!!! #####################
# Add only the name, not the type (only JPG)
# Hazardous_labels:
#  - explosive
#  - non_flammable_gas
#  - organic_peroxide
#  - dangerous_when_wet
#  - flammable_solid
#  # - flammable_liquid
#  # - poison_gas
#  # - spontaneously_combustible


# Hazardous_labels:[ explosive non_flammable_gas organic_peroxide dangerous_when_wet flammable_solid ]

# features:
#    - { x:167, y:49, lbp:[ 1, 0, 0, 1, 1, 0, 1, 1 ] }
#    - { x:298, y:130, lbp:[ 0, 0, 0, 1, 0, 0, 1, 1 ] }
#    - { x:344, y:158, lbp:[ 1, 1, 0, 0, 0, 0, 1, 0 ] }


# hazardous_labels:
 - name : "explosive"
 - name : "non_flammable_gas"
 - name : "organic_peroxide"
 - name : "dangerous_when_wet"
 - name : "flammable_solid"


 ########## only JPG!!!! #####################
# # Add only the name, not the type (only JPG)
# hazardous_labels:
#  - explosive
#  - non_flammable_gas
#  - organic_peroxide
#  - dangerous_when_wet
#  - flammable_solid