%YAML:1.0
YELLOW: !!opencv-matrix
   rows: 1
   cols: 6
   dt: i
   data: [ 12, 0, 176, 52, 255, 255 ]
ORANGE: !!opencv-matrix
   rows: 1
   cols: 6
   dt: i
   data: [ 0, 0, 0, 0, 0, 0 ]
RED: !!opencv-matrix
   rows: 1
   cols: 6
   dt: i
   data: [ 160, 73, 0, 185, 255, 255 ]
WALL: !!opencv-matrix
   rows: 1
   cols: 6
   dt: i
   data: [ 0, 0, 125, 23, 119, 255 ]
