%YAML:1.0
image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [855.443011, 0, 380.752837, 0, 850.137956, 237.496943, 0, 0, 1]
distortion_model: plumb_bob
distortion_matrix: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.091317, -0.142075, 0.002489, 0.027000, 0]
rectification_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: u
   data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [731.146301, 0, 282.034693, 0, 0, 732.697144, 248.931993, 0, 0, 0, 1, 0]